project:
  type: website
  output-dir: docs

website:
  title: "Elecciones Legislativas CABA 2025"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - text: |
          <link rel="stylesheet" href="_extensions/qmd-lab/closeread/closeread.css">
    resources:
      - _extensions/qmd-lab/closeread/closeread.css
      - _extensions/qmd-lab/closeread/closeread.js